name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Needed for deploy-pages
permissions:
  pages: write
  id-token: write
  contents: read

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  pages:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5
      # # (Optional) Node build; replace with your static-site build
      # - uses: actions/setup-node@v4
      #   with:
      #     node-version: 20
      #     cache: npm
      # - name: Build site
      #   run: |
      #     npm ci
      #     npm run build  # outputs to dist/

      # Upload the built site as a Pages artifact
      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      # Deploy the artifact to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
